name: vcd
channels:
  - defaults
dependencies:
  - python
  - numpy=1.16.4
  - h5py
  - Pillow=6.1
  - imageio=2.6.1
  - imageio-ffmpeg
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - moviepy
  - click
  - matplotlib
  - joblib
  - plotly
  - pip:
      - termcolor
      - scikit-image
      - opencv-python
      - pyquaternion==0.9.5
      - gtimer
      - gym==0.15.7
