defaults:
    - agent: sac

env: AntGoal-v0
expertpath: /home/aszot/expert_datasets/ant_50.pt

expertfrac: 0.5
env_noise: 0.03
gw_cover: 1.0
use_sqil: true

# this needs to be specified manually
experiment: test_exp

num_train_steps: 5e6
replay_buffer_capacity: 1e6

num_seed_steps: 5000

eval_frequency: 50000
num_eval_episodes: 100

device: cuda

# logger
log_frequency: 10000
log_save_tb: false
log_wb: true

# video recorder
save_video: true


seed: 1


# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./
